### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by DuBistKomisch** [electron/electron-notarize#28]
This would be useful for people not using this add-on as a JS hook in `electron-builder`. Similar to how `electron-osx-sign` has them.

Someone has made a separate `electron-notatize-cli` package, but it's inconvenient because of being tied to whatever version of this package it specifies as a dependency. I asked them to open a PR here instead but it seems like they're not interested: https://gitlab.com/fozi/electron-notarize-cli/issues/1

**Comment by malept** [comment]
I've generally come around to the opinion that CLI scripts should not be in tooling that function as libraries, because of the additional dependencies that are added. _(As an example, Electron Packager currently depends on a number of libraries that depend on `yargs`, `minimist`, `commander`, and `yargs-parser`, despite the Packager CLI only using `yargs-parser`.)_ I'd be OK with converting this into a monorepo and adding a CLI package. The main roadblocks I see currently are:

1. `semantic-release` does not yet support monorepos (although there are people who are trying to get it working).
2. Someone to actually do the work.

**Comment by f0zi** [comment]
Where would I subscribe to get (low noise!) notifications about releases?

**Comment by DuBistKomisch** [comment]
@f0zi I suppose the RSS feed of the repo releases/tags is the closest you'll get: https://github.com/electron/electron-notarize/releases.atom

@malept fair enough, one or two small extra dependencies doesn't seem like a lot when talking about electron though haha

**Comment by MarshallOfSound** [comment]
I personally don't think this library should have a CLI and didn't add one when it was originally written, it is very lightweight by itself and adding something like yargs or commander would be very unnecessary, writing your own CLI wrapper for notarize is trivial
